### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by abudq** [MoriyaShiine/superb-steeds#1]
### Mod version (NOT Minecraft version)

superbsteeds-1.20-1.jar -initial release

### A description of the issue

game crashed after looking on inventory tooltips, but I am not 100% sure

### Log or crash report

https://gist.github.com/abudq/c3d98fb075a0f7561dacc52c73c54fa0

**Comment by MoriyaShiine** [comment]
I changed how the armor value swapping works, it should have also probably fixed this
