### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by abudq** [MoriyaShiine/superb-steeds#2]
### Mod version (NOT Minecraft version)

superbsteeds-1.20-2

### A description of the issue

crash on start up, prob conflict with consistency plus. Disabling consistency plus - no crash on start up.

### Log or crash report

https://gist.github.com/abudq/c56e25c18e49520a8aea086bdfb0a2e1

**Comment by MoriyaShiine** [comment]
Sigh, they pass null as the name. I'll add a null check on my end but they should also fix that for any other mod that also expects the name to exist
