### ISSUE TITLE
Superb Steeds HUD shows on Llamas

### ISSUE THREAD

**Issue by anoomolu** [MoriyaShiine/superb-steeds#3]
### Mod version (NOT Minecraft version)

1.20-3

### A description of the issue

Taming a Llama, mounting it and opening the inventory displays the Superb Steeds HUD, despite being unable to control its movement at all. Would staying on the mob and letting it wander randomly eventually increase its speed/jump height? Maybe it could increase strength (the number of inventory slots it can have)?

Really minor issue so no worries if you'd rather close this.

### Log or crash report

https://gist.github.com/anoomolu/aabd69dd36857f08cc36aa6089ddd90d

**Comment by MoriyaShiine** [comment]
You can't train them, but I left it in because I thought it was funny. I might make it datapackable so mounts that can't be controlled don't get the gui but you could change if it you wanted to
